auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

# File scraping configuration
scrape_configs:
  - job_name: windsurf_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: windsurf
          __path__: /logs/*.log
    pipeline_stages:
      - match:
          selector: '{job="windsurf"}'
          stages:
            - regex:
                expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) (?P<level>\w+) (?P<message>.*)'
            - labels:
                level:
            - output:
                source: message

# Disable analytics
analytics:
  reporting_enabled: false
