server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /tmp/positions.yaml
  sync_period: 10s

clients:
  - url: http://loki:3100/loki/api/v1/push
    batchwait: 1s
    batchsize: 102400
    timeout: 10s
    backoff_config:
      min_period: 100ms
      max_period: 1s
      max_retries: 3

scrape_configs:
  - job_name: windsurf_logs
    pipeline_stages:
      - match:
          selector: '{job="windsurf"}'
          stages:
            - regex:
                expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) (?P<level>\w+) (?P<message>.*)'
            - labels:
                level:
            - output:
                source: message
    static_configs:
      - targets:
          - localhost
        labels:
          job: windsurf
          host: ${HOSTNAME}
          __path__: /logs/*.log
    relabel_configs:
      - source_labels: ['__path__']
        target_label: 'filename'
        replacement: '$1'
        action: 'replace'
